version: "3.3"
services:
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=message-center
    command: [ "--log_bin_trust_function_creators=1" ]
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
